version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 # dica do video do fullcycle pra rodar o container do mysql
    container_name: db
    restart: always # inicializa o container caso o mesmo caia
    tty: true # permite entrar no container
    volumes:
      - ./mysql:/var/lib/mysql # salva td do mysql do container localmente
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./node/files:/usr/src/app
    tty: true
    image: fredericotakayama/node:mk3
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - nodenet
    #ports:
    #  - "3000:3000"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: fredericotakayama/nginx:mk2
    container_name: nginx
    networks: 
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  nodenet:
    driver: bridge
