version: '3'

services:

  db:
    build:
      context: ./mysql_init
      dockerfile: Dockerfile.prod
    command: --innodb-use-native-aio=0 # dica do video do fullcycle pra rodar o container do mysql
    container_name: db
    restart: always # inicializa o container caso o mesmo caia
    tty: true # permite entrar no container
    volumes:
      #- ./mysql:/var/lib/mysql # salva td do mysql do container localmente
      - ./mysql_init:/docker-entrypoint-initdb.d # inicializa um script que tem no mysql_init
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    volumes:
      - ./node/files:/usr/src/app
    tty: true
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node